
import { Match, MatchScenario, Team } from '../types';

const TEAMS: Team[] = [
  { id: '1', name: '波士頓塞爾提克', shortName: 'BOS', logo: 'https://picsum.photos/seed/bos/100/100' },
  { id: '2', name: '金州勇士', shortName: 'GSW', logo: 'https://picsum.photos/seed/gsw/100/100' },
  { id: '3', name: '洛杉磯湖人', shortName: 'LAL', logo: 'https://picsum.photos/seed/lal/100/100' },
  { id: '4', name: '密爾瓦基公鹿', shortName: 'MIL', logo: 'https://picsum.photos/seed/mil/100/100' },
  { id: '5', name: '鳳凰城太陽', shortName: 'PHX', logo: 'https://picsum.photos/seed/phx/100/100' },
  { id: '6', name: '丹佛金塊', shortName: 'DEN', logo: 'https://picsum.photos/seed/den/100/100' },
];

export const generateMockMatches = (): Match[] => {
  const now = Date.now();
  return [
    {
      id: 'm1',
      homeTeam: TEAMS[0],
      awayTeam: TEAMS[1],
      homeScore: 0,
      awayScore: 0,
      status: 'SCHEDULED',
      homeOdds: 1.85,
      awayOdds: 1.95,
      spread: -1.5,
      scenario: MatchScenario.SIMILAR_STRENGTH,
      strongerTeamId: '1',
      quarter: 1,
      notifiedBuckets: [],
      maxDeficitRecorded: 0,
      recoverySteps: [],
      boughtTeamId: null,
      plStatus: null,
      scoreHistory: [0],
      startTime: now - 3600000,
    },
    {
      id: 'm2',
      homeTeam: TEAMS[2],
      awayTeam: TEAMS[3],
      homeScore: 0,
      awayScore: 0,
      status: 'SCHEDULED',
      homeOdds: 3.50,
      awayOdds: 1.30,
      spread: 8.5,
      scenario: MatchScenario.BIG_DIFFERENCE,
      strongerTeamId: '4',
      quarter: 1,
      notifiedBuckets: [],
      maxDeficitRecorded: 0,
      recoverySteps: [],
      boughtTeamId: null,
      plStatus: null,
      scoreHistory: [0],
      startTime: now - 1800000,
    },
    {
      id: 'm3',
      homeTeam: TEAMS[4],
      awayTeam: TEAMS[5],
      homeScore: 0,
      awayScore: 0,
      status: 'SCHEDULED',
      homeOdds: 2.10,
      awayOdds: 1.75,
      spread: -2.5,
      scenario: MatchScenario.SIMILAR_STRENGTH,
      strongerTeamId: '6',
      quarter: 1,
      notifiedBuckets: [],
      maxDeficitRecorded: 0,
      recoverySteps: [],
      boughtTeamId: null,
      plStatus: null,
      scoreHistory: [0],
      startTime: now,
    }
  ];
};
